// `registerTransactionBatchUpdate` has 9 Solidity params (+ self = 10); suppress clippy limit.
#![allow(clippy::too_many_arguments)]

use alloy::{primitives::B256, sol};
use plonky2::field::types::Field;
use tessera_trees::{tree::hasher::HashOutput, F};

sol! {
	#[sol(rpc)]
	interface IDepositsRollupBridge {
		// Keep this aligned with `DepositsRollupBridge.DepositStatus` in Solidity.
		enum DepositStatus { None, Pending, Validated, Withdrawn }

		// Keep this aligned with `DepositsRollupBridge.TreeType` in Solidity.
		// Do NOT reorder variants — values are stable across ABI versions.
		enum TreeType { NotesCommitment, NotesNullifier, AccountsCommitment, AccountsNullifier }

		struct Proof {
			uint256[8] proof;
			uint256[2] commitments;
			uint256[2] commitmentPok;
		}

		struct Deposit {
			uint256 value;
			address recipient;
			DepositStatus status;
		}

		// -------------------------------------------------------------------------
		// Existing view functions (latest roots, deposit-only path)
		// -------------------------------------------------------------------------
		function notesNullifierRoot() external view returns (bytes32);
		function notesCommitmentRoot() external view returns (bytes32);
		function accountsNullifierRoot() external view returns (bytes32);
		function accountsCommitmentRoot() external view returns (bytes32);
		function batchSize() external view returns (uint256);
		function getDeposit(bytes32 noteCommitment) external view returns (Deposit memory);
		function getDepositStatus(bytes32 noteCommitment) external view returns (DepositStatus);

		// -------------------------------------------------------------------------
		// Confirmed roots (advance per-tree as ZK proofs are verified).
		// Used for startup reconciliation; equal to the latest root on the deposit-only path.
		// -------------------------------------------------------------------------
		function confirmedNotesCommitmentRoot() external view returns (bytes32);
		function confirmedNotesNullifierRoot() external view returns (bytes32);
		function confirmedAccountsCommitmentRoot() external view returns (bytes32);
		function confirmedAccountsNullifierRoot() external view returns (bytes32);

		// -------------------------------------------------------------------------
		// Pending-batch slot getter (auto-generated by Solidity).
		// Note: bytes32[4] piCommitments is excluded from the Solidity auto-getter.
		// -------------------------------------------------------------------------
		function pendingBatches(uint256 slotIndex) external view returns (
			uint256 batchId,
			bytes32 newNotesCommitmentRoot,
			bytes32 newNotesNullifierRoot,
			bytes32 newAccountsCommitmentRoot,
			bytes32 newAccountsNullifierRoot,
			uint8 confirmedMask
		);

		// -------------------------------------------------------------------------
		// Deposit-only per-tree record functions (legacy path, still used for deposits)
		// -------------------------------------------------------------------------
		function recordNotesNullifierTreeUpdate(
			bytes32 newRoot,
			bytes32[] calldata noteCommitments,
			Proof calldata proof,
			Proof calldata aggregatedInputProof
		) external;
		function recordNotesCommitmentTreeUpdate(
			bytes32 newRoot,
			bytes32[] calldata noteCommitments,
			Proof calldata proof,
			Proof calldata aggregatedInputProof
		) external;
		function recordAccountsCommitmentTreeUpdate(
			bytes32 newRoot,
			bytes32[] calldata accountCommitments,
			Proof calldata proof,
			Proof calldata aggregatedInputProof
		) external;
		function recordAccountsNullifierTreeUpdate(
			bytes32 newRoot,
			bytes32[] calldata accountCommitments,
			Proof calldata proof,
			Proof calldata aggregatedInputProof
		) external;

		// -------------------------------------------------------------------------
		// Two-phase transaction-batch API
		// -------------------------------------------------------------------------

		/// Optimistically registers all four tree roots and stores PI commitments.
		/// Returns the 1-based batch ID assigned to this batch.
		function registerTransactionBatchUpdate(
			bytes32 newNotesCommitmentRoot,
			bytes32[] calldata noteCommitmentsOut,
			bytes32 newNotesNullifierRoot,
			bytes32[] calldata noteNullifiersIn,
			bytes32 newAccountsCommitmentRoot,
			bytes32[] calldata accountCommitmentsOut,
			bytes32 newAccountsNullifierRoot,
			bytes32[] calldata accountNullifiersIn,
			bytes32[4] calldata piCommitments
		) external returns (uint256 batchId);

		/// Confirms one tree's ZK proof for a previously registered batch.
		/// Frees the slot and emits TransactionBatchConfirmed once all four trees are confirmed.
		function confirmTreeUpdate(
			uint256 batchId,
			uint8 treeIndex,
			Proof calldata treeProof,
			Proof calldata inputsProof
		) external;

		// -------------------------------------------------------------------------
		// Events
		// -------------------------------------------------------------------------
		event DepositAvailable(
			bytes32 indexed noteCommitment,
			uint256 value,
			address recipient
		);

		/// `treeType` is indexed so indexers can filter by tree without decoding calldata.
		event ValidatedBatchFinalized(
			TreeType indexed treeType,
			uint256 batchSize,
			bytes32 oldRoot,
			bytes32 newRoot
		);

		event DepositValidated(bytes32 indexed noteCommitment);

		/// Emitted by registerTransactionBatchUpdate.
		event TransactionBatchRegistered(
			uint256 indexed batchId,
			bytes32 newNotesCommitmentRoot,
			bytes32 newNotesNullifierRoot,
			bytes32 newAccountsCommitmentRoot,
			bytes32 newAccountsNullifierRoot,
			bytes32[4] piCommitments
		);

		/// Emitted by confirmTreeUpdate for each successfully confirmed tree.
		event TreeUpdateConfirmed(uint256 indexed batchId, uint8 treeIndex);

		/// Emitted when all four trees in a batch are confirmed (confirmedMask == 0xF).
		event TransactionBatchConfirmed(uint256 indexed batchId);

		// -------------------------------------------------------------------------
		// Errors
		// -------------------------------------------------------------------------
		error PendingQueueFull();
		error SlotConflict(uint256 slotIndex);
		error UnknownBatch(uint256 batchId);
		error AlreadyConfirmed(uint256 batchId, uint8 treeIndex);
		error InvalidTreeIndex(uint8 treeIndex);
	}
}

/// Convert a `Hash` (4 Goldilocks field elements) to `bytes32`.
///
/// Encoding: each element as 8-byte big-endian uint64, concatenated.
/// Matches the convention in `groth16_wrapper.rs` and `DepositsRollupBridge.sol`.
pub fn hash_to_bytes32(h: &HashOutput) -> B256 {
	let mut bytes = [0u8; 32];
	for i in 0..4 {
		bytes[i * 8..(i + 1) * 8].copy_from_slice(&h.0[i].0.to_be_bytes());
	}
	B256::from(bytes)
}

/// The Goldilocks prime: 2^64 - 2^32 + 1.
pub const GOLDILOCKS_PRIME: u64 = 0xFFFF_FFFF_0000_0001;

/// Convert a `bytes32` (from on-chain commitment) to a `Hash`.
///
/// Inverse of `hash_to_bytes32`. Each 8-byte big-endian chunk becomes a
/// Goldilocks field element.
///
/// # Errors
/// Returns `Err` if any of the four 64-bit limbs is ≥ `GOLDILOCKS_PRIME`
/// (2^64 - 2^32 + 1). Such values are outside the Goldilocks field and would
/// silently produce an incorrect element if passed to
/// `F::from_canonical_u64`, breaking root derivation and proof verification.
pub fn bytes32_to_hash(b: &B256) -> anyhow::Result<HashOutput> {
	let bytes = b.as_slice();
	let mut elems = [F::ZERO; 4];
	for i in 0..4 {
		let val = u64::from_be_bytes(
			bytes[i * 8..(i + 1) * 8]
				.try_into()
				.expect("slice is always 8 bytes"),
		);
		anyhow::ensure!(
			val < GOLDILOCKS_PRIME,
			"bytes32 limb {} out of Goldilocks field range: {:#018x} >= {:#018x}",
			i,
			val,
			GOLDILOCKS_PRIME
		);
		elems[i] = F::from_canonical_u64(val);
	}
	Ok(HashOutput(elems))
}

/// Convert a slice of raw 32-byte commitments to validated Goldilocks `Hash`
/// values, failing immediately if any limb is out of range.
///
/// This is the preferred helper for the many `.map(bytes32_to_hash).collect()`
/// patterns in the sequencer so that error propagation is uniform.
pub fn bytes_slice_to_hashes(raw: &[[u8; 32]]) -> anyhow::Result<Vec<HashOutput>> {
	raw.iter()
		.map(|b| bytes32_to_hash(&B256::from(*b)))
		.collect()
}
