use anyhow::Result;
use plonky2::{
	field::extension::Extendable,
	hash::hash_types::RichField,
	iop::witness::PartialWitness,
	plonk::{
		circuit_builder::CircuitBuilder,
		circuit_data::{CircuitConfig, CircuitData},
		config::{AlgebraicHasher, GenericConfig},
		proof::ProofWithPublicInputs,
	},
};

use crate::tree::{
	NullifierInsertProof, NullifierInsertProofTargets,
	hasher::{MerkleHash, MerkleHashCircuit, ToHashOut},
};

/// A reusable STARK proof generator for leaf insertions.
///
/// This struct holds a pre-built circuit that can be reused to generate
/// STARK proofs for multiple leaf insertions. Building the circuit once
/// and reusing it is much more efficient than rebuilding for each proof.
///
/// # Type Parameters
/// * `H` - The hash function used (must implement `MerkleHash` and `MerkleHashCircuit`)
/// * `F` - The field type (typically `GoldilocksField`)
/// * `C` - The circuit configuration (typically `PoseidonGoldilocksConfig`)
/// * `D` - The extension degree (typically 2)
/// * `DEPTH` - The Merkle tree depth (const generic)
///
/// # Example
///
/// ```ignore
/// // Create the generator once at startup
/// let generator = InsertProofGenerator::<Hash, F, C, D, 32>::new();
///
/// // For each insertion, generate a STARK proof
/// let native_proof = tree.insert_node::<32>(node)?;
/// let stark_proof = generator.prove(&native_proof)?;
///
/// // The STARK proof can be sent to the aggregator
/// aggregator.submit_with_position(position, stark_proof);
/// ```
pub struct ProofGenerator<
	H: MerkleHash + MerkleHashCircuit<F, D>,
	F: RichField + Extendable<D>,
	C: GenericConfig<D, F = F>,
	const D: usize,
	const DEPTH: usize,
> where
	<H as MerkleHash>::Digest: ToHashOut<F>,
{
	/// The pre-built circuit data
	pub circuit_data: CircuitData<F, C, D>,
	/// The circuit targets for setting witnesses
	targets: NullifierInsertProofTargets,
	/// Phantom data for the hash type
	_phantom: std::marker::PhantomData<H>,
}

impl<H, F, C, const D: usize, const DEPTH: usize> ProofGenerator<H, F, C, D, DEPTH>
where
	H: MerkleHash + MerkleHashCircuit<F, D>,
	<H as MerkleHash>::Digest: ToHashOut<F>,
	F: RichField + Extendable<D>,
	C: GenericConfig<D, F = F>,
	C::Hasher: AlgebraicHasher<F>,
{
	/// Creates a new proof generator with default circuit configuration.
	///
	/// This builds the circuit once, which can then be reused for multiple proofs.
	/// Circuit building is expensive, so this should be done once at startup.
	pub fn new() -> Self {
		Self::with_config(CircuitConfig::standard_recursion_config())
	}

	/// Creates a new proof generator with a custom circuit configuration.
	///
	/// # Arguments
	/// * `config` - The circuit configuration to use
	pub fn with_config(config: CircuitConfig) -> Self {
		let mut builder: CircuitBuilder<F, D> = CircuitBuilder::<F, D>::new(config);

		// Allocate targets
		let targets: NullifierInsertProofTargets =
			NullifierInsertProofTargets::new(&mut builder, DEPTH, true, true);

		// Connect constraints
		targets.connect::<H, F, D>(&mut builder);

		// Build the circuit
		let circuit_data: CircuitData<F, C, D> = builder.build::<C>();

		Self {
			circuit_data,
			targets,
			_phantom: std::marker::PhantomData,
		}
	}

	/// Generates a STARK proof from a native insertion proof.
	///
	/// # Arguments
	/// * `proof` - The native insertion proof from `IndexedMerkleTree::insert_node()`
	///
	/// # Returns
	/// A STARK proof that can be verified or aggregated.
	///
	/// # Errors
	/// Returns an error if witness setting or proving fails.
	pub fn prove(&self, proof: &NullifierInsertProof<H>) -> Result<ProofWithPublicInputs<F, C, D>> {
		let mut pw: PartialWitness<F> = PartialWitness::new();
		self.targets.set::<H, F, DEPTH>(&mut pw, proof)?;
		let circuit_proof: ProofWithPublicInputs<F, C, D> = self.circuit_data.prove(pw)?;
		Ok(circuit_proof)
	}

	/// Verifies a STARK proof generated by this generator.
	///
	/// # Arguments
	/// * `proof` - The STARK proof to verify
	///
	/// # Returns
	/// Ok(()) if verification succeeds, Err otherwise.
	pub fn verify(&self, proof: &ProofWithPublicInputs<F, C, D>) -> Result<()> {
		self.circuit_data.verify(proof.clone())?;
		Ok(())
	}

	/// Returns the common circuit data (needed for aggregation).
	pub fn common_data(&self) -> &plonky2::plonk::circuit_data::CommonCircuitData<F, D> {
		&self.circuit_data.common
	}

	/// Returns the verifier-only circuit data (needed for aggregation).
	pub fn verifier_data(&self) -> &plonky2::plonk::circuit_data::VerifierOnlyCircuitData<C, D> {
		&self.circuit_data.verifier_only
	}

	/// Returns the tree depth this generator was built for.
	pub fn depth(&self) -> usize {
		DEPTH
	}
}

impl<H, F, C, const D: usize, const DEPTH: usize> Default for ProofGenerator<H, F, C, D, DEPTH>
where
	H: MerkleHash + MerkleHashCircuit<F, D>,
	<H as MerkleHash>::Digest: ToHashOut<F>,
	F: RichField + Extendable<D>,
	C: GenericConfig<D, F = F>,
	C::Hasher: AlgebraicHasher<F>,
{
	fn default() -> Self {
		Self::new()
	}
}

#[cfg(test)]
mod test {
	use std::time::Instant;

	use anyhow::Result;
	use plonky2::{
		field::goldilocks_field::GoldilocksField, plonk::config::PoseidonGoldilocksConfig,
	};

	use crate::tree::{
		NullifierTree, ProofGenerator, StreamingAggregator,
		hasher::{HashOutput, NewFromU64},
	};

	const D: usize = 2;
	pub type C = PoseidonGoldilocksConfig;
	pub type F = GoldilocksField;

	#[test]
	fn test_insert_proof_generator() -> Result<()> {
		const DEPTH: usize = 32;

		println!("=== InsertProofGenerator Test ===\n");

		// Create tree
		print!("Create tree: ");
		let now = Instant::now();
		let mut tree: NullifierTree<HashOutput> = NullifierTree::new(DEPTH);
		println!("{:?}", now.elapsed());

		// Create generator (this builds the circuit once)
		print!("Create generator (build circuit): ");
		let now = Instant::now();
		let generator = ProofGenerator::<HashOutput, F, C, D, DEPTH>::new();
		println!("{:?}", now.elapsed());

		// Insert multiple values and generate STARK proofs
		for i in 0..3 {
			println!("\n--- Insertion {} ---", i);

			// Insert value and get native proof
			print!("  Insert value: ");
			let now = Instant::now();
			let value = HashOutput::new_from_u64((i + 1) as u64 * 100);
			let native_proof = tree.insert(value)?;
			println!("{:?}", now.elapsed());

			// Verify native proof
			assert!(native_proof.verify(), "Native proof failed");

			// Generate STARK proof using the generator
			print!("  Generate STARK proof: ");
			let now = Instant::now();
			let stark_proof = generator.prove(&native_proof)?;
			println!("{:?}", now.elapsed());

			// Verify STARK proof
			print!("  Verify STARK proof: ");
			let now = Instant::now();
			generator.verify(&stark_proof)?;
			println!("{:?}", now.elapsed());

			// Check public inputs
			println!("  Public inputs: {}", stark_proof.public_inputs.len());
		}

		println!("\n=== Generator test passed! ===");
		Ok(())
	}

	#[test]
	fn test_generator_with_aggregator() -> Result<()> {
		const DEPTH: usize = 32;
		const NUM_PROOFS: usize = 4;
		const AGG_DEPTH: usize = 2; // log2(4) = 2

		println!("=== Generator + Aggregator Integration Test ===\n");

		// Create tree and generator
		let mut tree: NullifierTree<HashOutput> = NullifierTree::new(DEPTH);
		let generator = ProofGenerator::<HashOutput, F, C, D, DEPTH>::new();

		// Create aggregator using the generator's circuit data
		let aggregator = StreamingAggregator::<F, C, D>::new(
			generator.common_data().clone(),
			generator.verifier_data().clone(),
			AGG_DEPTH,
		);

		println!(
			"Generating {} STARK proofs and submitting to aggregator...",
			NUM_PROOFS
		);
		let now = std::time::Instant::now();

		for i in 0..NUM_PROOFS {
			// Insert and generate STARK proof
			let value = HashOutput::new_from_u64((i + 1) as u64 * 100);
			let native_proof = tree.insert(value)?;
			let stark_proof = generator.prove(&native_proof)?;

			// Submit to aggregator
			aggregator.submit_with_position(i, stark_proof);
			println!("  Submitted proof {}", i);
		}

		// Wait for aggregation result
		let result = aggregator.take_result()?;
		println!("Aggregation completed in {:?}", now.elapsed());

		// Verify aggregated proof
		result.verify()?;
		println!("Aggregated proof verified!");

		println!("\n=== Integration test passed! ===");
		Ok(())
	}
}
