// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {DepositsRollupBridge, IGroth16Verifier} from "../src/DepositsRollupBridge.sol";
import {Verifier} from "../src/Verifier128.sol";

/// @title  Integration test: real Verifier128 + DepositsRollupBridge (two-phase)
/// @notice Loads a Groth16 proof and bridge calldata generated by the Rust
///         `groth16_wrapper` example and executes a full two-phase cycle:
///         submitBatch (Pending) → finalizeBatch (Validated).
///
///         Artifact files (in groth-artifacts/):
///           - proof_solidity.json:  { proof[8], commitments[2], commitmentPok[2] }
///           - bridge_calldata.json: { oldRoot, newRoot, leaves, deposits[] }
///
///         The test uses dummy deposits because proof verification depends on
///         the `leaves` parameter (SHA-256 commitment), not the raw deposit
///         data. Deposits are stored for data availability only.
///
///         Prerequisites:
///           1. Run `cargo run --example groth16_wrapper --release` in tessera-trees
///              (generates proof_solidity.json + bridge_calldata.json)
///           2. Run `forge test --match-contract Integration -vv`
contract DepositsRollupBridgeIntegrationTest is Test {
    string constant ARTIFACTS = "../tessera-trees/examples/tmp/groth-artifacts/";

    DepositsRollupBridge public bridge;
    Verifier public verifier;

    address public operator = address(this);

    // ---------------------------------------------------------------
    // Setup
    // ---------------------------------------------------------------

    function setUp() public {
        verifier = new Verifier();
    }

    // ---------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------

    struct ProofJson {
        uint256[8] proof;
        uint256[2] commitments;
        uint256[2] commitmentPok;
    }

    function _loadProofJson() internal view returns (ProofJson memory p) {
        string memory json = vm.readFile(
            string.concat(ARTIFACTS, "proof_solidity.json")
        );

        bytes memory rawProof = vm.parseJson(json, ".proof");
        uint256[] memory proofArr = abi.decode(rawProof, (uint256[]));
        for (uint256 i = 0; i < 8; i++) {
            p.proof[i] = proofArr[i];
        }

        bytes memory rawCommitments = vm.parseJson(json, ".commitments");
        uint256[] memory commArr = abi.decode(rawCommitments, (uint256[]));
        for (uint256 i = 0; i < 2; i++) {
            p.commitments[i] = commArr[i];
        }

        bytes memory rawPok = vm.parseJson(json, ".commitmentPok");
        uint256[] memory pokArr = abi.decode(rawPok, (uint256[]));
        for (uint256 i = 0; i < 2; i++) {
            p.commitmentPok[i] = pokArr[i];
        }
    }

    struct BridgeCalldata {
        bytes32 oldRoot;
        bytes32 newRoot;
        bytes leaves;
    }

    function _loadBridgeCalldata() internal view returns (BridgeCalldata memory c) {
        string memory json = vm.readFile(
            string.concat(ARTIFACTS, "bridge_calldata.json")
        );

        c.oldRoot = vm.parseJsonBytes32(json, ".oldRoot");
        c.newRoot = vm.parseJsonBytes32(json, ".newRoot");
        c.leaves = vm.parseJsonBytes(json, ".leaves");
    }

    /// @dev Load deposits from bridge_calldata.json if present, otherwise
    ///      generate dummy deposits (for backwards compatibility with
    ///      artifacts that don't yet include deposit data).
    function _loadOrDummyDeposits(string memory json)
        internal
        pure
        returns (DepositsRollupBridge.Deposit[] memory deps)
    {
        deps = new DepositsRollupBridge.Deposit[](128);

        // Try to parse deposits array.
        bytes memory raw = vm.parseJson(json, ".deposits");
        if (raw.length > 0) {
            // Deposits present — decode array of tuples.
            // Each deposit encoded as (bytes32, uint64, uint64, uint64, uint64).
            (
                bytes32[] memory noteCommitments,
                uint64[] memory addr0s,
                uint64[] memory addr1s,
                uint64[] memory addr2s,
                uint64[] memory amounts
            ) = abi.decode(raw, (bytes32[], uint64[], uint64[], uint64[], uint64[]));

            for (uint256 i = 0; i < 128; i++) {
                deps[i] = DepositsRollupBridge.Deposit({
                    noteCommitment: noteCommitments[i],
                    addr0: addr0s[i],
                    addr1: addr1s[i],
                    addr2: addr2s[i],
                    amount: amounts[i]
                });
            }
        } else {
            // No deposits in JSON — use deterministic dummies.
            // The contract stores them but they don't affect proof verification
            // (the leaves parameter is what matters for the SHA-256 commitment).
            for (uint256 i = 0; i < 128; i++) {
                uint256 v = uint256(keccak256(abi.encode(uint8(0), i)));
                deps[i] = DepositsRollupBridge.Deposit({
                    noteCommitment: bytes32(v),
                    addr0: uint64(v),
                    addr1: uint64(v >> 64),
                    addr2: uint64(v >> 128),
                    amount: uint64(v >> 192)
                });
            }
        }
    }

    // ---------------------------------------------------------------
    // Integration test
    // ---------------------------------------------------------------

    /// @notice Full end-to-end test: submitBatch → finalizeBatch with the
    ///         real Groth16 verifier.
    function testIntegration_SubmitAndFinalize() public {
        // 1. Load test data from Rust-generated artifacts.
        ProofJson memory proofData = _loadProofJson();
        BridgeCalldata memory callData = _loadBridgeCalldata();

        // 2. Deploy bridge with the real verifier and correct genesis root.
        bridge = new DepositsRollupBridge(
            address(verifier),
            operator,
            callData.oldRoot
        );
        assertEq(bridge.stateRoot(), callData.oldRoot, "genesis root mismatch");

        // 3. Build dummy deposits (proof verification depends on leaves, not deposits).
        DepositsRollupBridge.Deposit[] memory deps =
            new DepositsRollupBridge.Deposit[](128);
        for (uint256 i = 0; i < 128; i++) {
            uint256 v = uint256(keccak256(abi.encode(uint8(0), i)));
            deps[i] = DepositsRollupBridge.Deposit({
                noteCommitment: bytes32(v),
                addr0: uint64(v),
                addr1: uint64(v >> 64),
                addr2: uint64(v >> 128),
                amount: uint64(v >> 192)
            });
        }

        // 4. Submit the batch → enters pending pool.
        bytes32 commit = bridge.submitBatch(
            callData.newRoot,
            deps,
            callData.leaves
        );

        // Sanity: batch is pending.
        (, , , , DepositsRollupBridge.BatchStatus statusBefore, ) = bridge.getBatch(commit);
        assertTrue(
            statusBefore == DepositsRollupBridge.BatchStatus.Pending,
            "batch should be pending"
        );

        // 5. Log public inputs for debugging.
        bytes32 sha256Commit = sha256(
            abi.encodePacked(callData.oldRoot, callData.newRoot, callData.leaves)
        );
        uint256[8] memory expectedInputs = bridge.sha256ToPublicInputs(sha256Commit);
        emit log_named_bytes32("sha256Commit", sha256Commit);
        for (uint256 i = 0; i < 8; i++) {
            emit log_named_uint(
                string.concat("pubInput[", vm.toString(i), "]"),
                expectedInputs[i]
            );
        }

        // 6. Build the proof struct.
        DepositsRollupBridge.Proof memory proof;
        proof.proof = proofData.proof;
        proof.commitments = proofData.commitments;
        proof.commitmentPok = proofData.commitmentPok;

        // 7. Finalize — calls the real Verifier128.
        bridge.finalizeBatch(commit, proof);

        // 8. Verify state was updated.
        assertEq(bridge.stateRoot(), callData.newRoot, "root not updated");
        assertEq(bridge.batchNumber(), 1, "batch number not incremented");

        // 9. Batch moved to validated pool.
        (, , , , DepositsRollupBridge.BatchStatus statusAfter, uint256 depsCount) =
            bridge.getBatch(commit);
        assertTrue(
            statusAfter == DepositsRollupBridge.BatchStatus.Validated,
            "batch should be validated"
        );
        assertEq(depsCount, 128, "deposits count mismatch");
    }
}
