// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script, console} from "forge-std/Script.sol";
import {PoseidonGoldilocks} from "../src/PoseidonGoldilocks.sol";
import {TesseraContract} from "../src/TesseraContract.sol";
import {TesseraBatchTransactionVerifier} from "../src/TesseraBatchTransactionVerifier.sol";
import {ToyUSDT} from "../src/ToyUSDT.sol";
import {ToyUser} from "../src/ToyUser.sol";

/// @title  Deploy TesseraContract + supporting contracts
/// @notice Deploys the full V2 stack to the target chain. The deployer
///         (`msg.sender`) is set as the initial operator.
///
///         Run the Rust artifact generator before deploying to ensure the
///         real gnark Groth16 verifier is in src/TesseraBatchTransactionVerifier.sol:
///           cargo run --bin super_aggregator_v2_artifacts --release
///
/// Required environment variables:
///   TESSERA_TREE_DEPTH         -- depth of the on-chain Poseidon Merkle tree (e.g. 20)
///   TESSERA_CONFIG_TREE_DEPTH  -- depth of the subpool config Merkle tree (e.g. 20)
///
/// Optional:
///   TESSERA_TX_VERIFIER        -- pre-deployed Groth16 tx-batch verifier address
///                                 (deploys a fresh TesseraBatchTransactionVerifier if unset)
///   TESSERA_DEPOSIT_VERIFIER   -- pre-deployed Groth16 deposit-batch verifier address
///                                 (reuses txVerifier address if unset — same circuit)
///   TESSERA_MONITORED_TOKEN    -- ERC20 address escrowed by the bridge
///                                 (deploys a fresh ToyUSDT if unset)
///   TESSERA_OPERATOR           -- operator address (defaults to msg.sender)
///   TESSERA_WITHDRAWAL_DELAY   -- minimum blocks between deposit and withdrawal (default: 0)
contract DeployScript is Script {
    function run() external {
        uint256 treeDepth        = vm.envUint("TESSERA_TREE_DEPTH");
        uint256 configTreeDepth  = vm.envUint("TESSERA_CONFIG_TREE_DEPTH");
        uint256 withdrawalDelay  = vm.envOr("TESSERA_WITHDRAWAL_DELAY", uint256(0));

        address txVerifier      = vm.envOr("TESSERA_TX_VERIFIER",      address(0));
        address depositVerifier = vm.envOr("TESSERA_DEPOSIT_VERIFIER", address(0));
        address monitoredToken  = vm.envOr("TESSERA_MONITORED_TOKEN",  address(0));
        address operator        = vm.envOr("TESSERA_OPERATOR",         msg.sender);

        vm.startBroadcast();

        // 1. PoseidonGoldilocks hash contract.
        PoseidonGoldilocks poseidon = new PoseidonGoldilocks();
        console.log("PoseidonGoldilocks:  ", address(poseidon));

        // 2. Groth16 tx-batch verifier — deploy fresh if address not provided.
        //    NOTE: TesseraBatchTransactionVerifier.sol must have been generated by
        //    `super_aggregator_v2_artifacts`; the placeholder always reverts.
        if (txVerifier == address(0)) {
            txVerifier = address(new TesseraBatchTransactionVerifier());
            console.log("VerifierTxBatch (fresh): ", txVerifier);
        } else {
            console.log("TxVerifier:          ", txVerifier);
        }

        // 3. Groth16 deposit-batch verifier.
        //    Both TX and deposit proofs use the same Final Plonky2 Proof circuit until a
        //    dedicated consume circuit is built (see prover_v2.rs).
        if (depositVerifier == address(0)) {
            depositVerifier = txVerifier;
            console.log("DepositVerifier:     ", depositVerifier, "(reuses txVerifier)");
        } else {
            console.log("DepositVerifier:     ", depositVerifier);
        }

        // 4. ERC20 token — deploy ToyUSDT if no address provided.
        if (monitoredToken == address(0)) {
            monitoredToken = address(new ToyUSDT());
            console.log("ToyUSDT (fresh):     ", monitoredToken);
        } else {
            console.log("MonitoredToken:      ", monitoredToken);
        }

        // 5. Main rollup contract.
        //    mainPoolConfigRoot is computed at construction as the genesis root of an
        //    all-zero configTreeDepth-deep Poseidon binary Merkle tree.
        TesseraContract rollup = new TesseraContract(
            txVerifier,
            depositVerifier,
            address(poseidon),
            operator,
            treeDepth,
            configTreeDepth,
            withdrawalDelay
        );
        console.log("TesseraContract:     ", address(rollup));

        // 6. ToyUser helper (optional convenience wrapper for E2E tests).
        ToyUser toyUser = new ToyUser(address(rollup), monitoredToken);
        console.log("ToyUser:             ", address(toyUser));

        vm.stopBroadcast();

        console.log("\n--- Deployment summary ---");
        console.log("Operator:            ", operator);
        console.log("Tree depth:          ", treeDepth);
        console.log("Config tree depth:   ", configTreeDepth);
        console.log("Withdrawal delay:    ", withdrawalDelay);
        console.log("Genesis tree root:   ", rollup.imtCurrentRoot());
        console.log("Genesis config root: ", rollup.mainPoolConfigRoot());
    }
}
