// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script, console} from "forge-std/Script.sol";
import {PoseidonGoldilocks} from "../src/PoseidonGoldilocks.sol";
import {TesseraRollupV2} from "../src/TesseraRollupV2.sol";
import {VerifierSuperAggregatorV2} from "../src/VerifierSuperAggregatorV2.sol";
import {AcceptAllVerifier} from "../src/AcceptAllVerifier.sol";
import {ToyUSDT} from "../src/ToyUSDT.sol";
import {ToyUser} from "../src/ToyUser.sol";

/// @title  Deploy TesseraRollupV2 + supporting contracts
/// @notice Deploys the full V2 stack to the target chain. The deployer
///         (`msg.sender`) is set as the initial operator.
///
///         Run the Rust artifact generator before deploying to ensure the
///         real gnark Groth16 verifier is in src/VerifierSuperAggregatorV2.sol:
///           cargo run --bin super_aggregator_v2_artifacts --release
///
/// Required environment variables:
///   TESSERA_POOL_CONFIG_ROOT -- bytes32 initial pool configuration root
///   TESSERA_TREE_DEPTH       -- depth of the on-chain Poseidon Merkle tree (e.g. 20)
///
/// Optional:
///   TESSERA_TX_VERIFIER      -- pre-deployed Groth16 tx-batch verifier address
///                               (deploys a fresh VerifierSuperAggregatorV2 if unset)
///   TESSERA_DEPOSIT_VERIFIER -- pre-deployed Groth16 deposit-batch verifier address
///                               (reuses txVerifier address if unset — same circuit)
///   TESSERA_MONITORED_TOKEN  -- ERC20 address escrowed by the bridge
///                               (deploys a fresh ToyUSDT if unset)
///   TESSERA_OPERATOR         -- operator address (defaults to msg.sender)
contract DeployScript is Script {
    function run() external {
        bytes32 poolConfigRoot = vm.envBytes32("TESSERA_POOL_CONFIG_ROOT");
        uint256 treeDepth      = vm.envUint("TESSERA_TREE_DEPTH");

        address txVerifier      = vm.envOr("TESSERA_TX_VERIFIER",      address(0));
        address depositVerifier = vm.envOr("TESSERA_DEPOSIT_VERIFIER", address(0));
        address monitoredToken  = vm.envOr("TESSERA_MONITORED_TOKEN",  address(0));
        address operator        = vm.envOr("TESSERA_OPERATOR",         msg.sender);

        vm.startBroadcast();

        // 1. PoseidonGoldilocks hash contract.
        PoseidonGoldilocks poseidon = new PoseidonGoldilocks();
        console.log("PoseidonGoldilocks:  ", address(poseidon));

        // 2. Groth16 tx-batch verifier — deploy fresh if address not provided.
        //    NOTE: VerifierSuperAggregatorV2.sol must have been generated by
        //    `super_aggregator_v2_artifacts`; the placeholder always reverts.
        if (txVerifier == address(0)) {
            txVerifier = address(new VerifierSuperAggregatorV2());
            console.log("VerifierTxBatch (fresh): ", txVerifier);
        } else {
            console.log("TxVerifier:          ", txVerifier);
        }

        // 3. Groth16 deposit-batch verifier.
        //    Both TX and deposit proofs use the same SAV2 circuit until a
        //    dedicated consume circuit is built (see prover_v2.rs).
        if (depositVerifier == address(0)) {
            depositVerifier = txVerifier;
            console.log("DepositVerifier:     ", depositVerifier, "(reuses txVerifier)");
        } else {
            console.log("DepositVerifier:     ", depositVerifier);
        }

        // 4. ERC20 token — deploy ToyUSDT if no address provided.
        if (monitoredToken == address(0)) {
            monitoredToken = address(new ToyUSDT());
            console.log("ToyUSDT (fresh):     ", monitoredToken);
        } else {
            console.log("MonitoredToken:      ", monitoredToken);
        }

        // 5. Main rollup contract.
        TesseraRollupV2 rollup = new TesseraRollupV2(
            txVerifier,
            depositVerifier,
            address(poseidon),
            operator,
            monitoredToken,
            poolConfigRoot,
            treeDepth
        );
        console.log("TesseraRollupV2:     ", address(rollup));

        // 6. ToyUser helper (optional convenience wrapper for E2E tests).
        ToyUser toyUser = new ToyUser(address(rollup), monitoredToken);
        console.log("ToyUser:             ", address(toyUser));

        vm.stopBroadcast();

        console.log("\n--- Deployment summary ---");
        console.log("Operator:            ", operator);
        console.log("Tree depth:          ", treeDepth);
        console.log("Pool config root:    ", uint256(poolConfigRoot));
        console.log("Genesis tree root:   ", rollup.currentRoot());
    }
}
