#!/usr/bin/env bash
set -euo pipefail

# Step B: deploy the demo contract stack.
#
# Deploys: AcceptAllVerifier, PoseidonGoldilocks, ToyUSDT, TesseraContract.
# Uses AcceptAllVerifier for BOTH tx and deposit verifiers (zero proofs accepted).
#
# Prerequisites:
#   - Anvil running (scripts/demo_a_anvil.sh)
#   - forge + cast available

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/env/priv_env.sh"

mkdir -p "$DEMO_LOG_DIR"

echo ""
echo "Checking RPC connectivity: $RPC"
cast block-number --rpc-url "$RPC" >/dev/null

SOLIDITY_DIR="$ROOT_DIR/tessera-solidity"

pushd "$SOLIDITY_DIR" >/dev/null

# 1. Deploy AcceptAllVerifier
echo ""
echo "Deploying AcceptAllVerifier..."
ACCEPT_OUT=$(forge create src/AcceptAllVerifier.sol:AcceptAllVerifier \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast 2>&1)
echo "$ACCEPT_OUT"
ACCEPT_ADDR=$(echo "$ACCEPT_OUT" | grep -oP 'Deployed to: \K0x[0-9a-fA-F]+')
echo "  AcceptAllVerifier = $ACCEPT_ADDR"

# 2. Deploy using the existing Deploy.s.sol with AcceptAllVerifier as tx/deposit verifier.
echo ""
echo "Deploying full stack (PoseidonGoldilocks + ToyUSDT + TesseraContract + ToyUser)..."

TESSERA_TX_VERIFIER="$ACCEPT_ADDR" \
TESSERA_DEPOSIT_VERIFIER="$ACCEPT_ADDR" \
TESSERA_POOL_CONFIG_ROOT="$POOL_CONFIG_ROOT" \
TESSERA_TREE_DEPTH="$TREE_DEPTH" \
forge script script/Deploy.s.sol \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast 2>&1

popd >/dev/null

# Parse deployed addresses from broadcast JSON.
BROADCAST_JSON="$SOLIDITY_DIR/broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"
if [[ ! -f "$BROADCAST_JSON" ]]; then
  echo "ERROR: broadcast file not found: $BROADCAST_JSON" >&2
  exit 1
fi

ROLLUP=$(jq -r '.transactions[] | select(.contractName == "TesseraContract") | .contractAddress' "$BROADCAST_JSON" | head -n1)
TOKEN=$(jq -r '.transactions[] | select(.contractName == "ToyUSDT") | .contractAddress' "$BROADCAST_JSON" | head -n1)

if [[ -z "${ROLLUP:-}" ]]; then
  echo "ERROR: failed to parse TesseraContract address." >&2
  exit 1
fi
if [[ -z "${TOKEN:-}" ]]; then
  echo "ERROR: failed to parse ToyUSDT address." >&2
  exit 1
fi

# Read genesis root from on-chain.
GENESIS_ROOT=$(cast call "$ROLLUP" "currentRoot()(uint256)" --rpc-url "$RPC" | tr -d '[:space:]' | sed 's/\[.*\]//')

# Derive operator address from key.
OPERATOR_ADDR=$(cast wallet address --private-key "$OPERATOR_KEY")

echo ""
echo "=== Deployment summary ==="
echo "  AcceptAllVerifier  = $ACCEPT_ADDR"
echo "  TesseraContract    = $ROLLUP"
echo "  ToyUSDT            = $TOKEN"
echo "  Operator            = $OPERATOR_ADDR"
echo "  Genesis root        = $GENESIS_ROOT"

# Write state file for subsequent scripts.
cat > "$DEMO_STATE_ENV" <<EOV
# Auto-generated by scripts/demo_b_deploy.sh
export ROLLUP="$ROLLUP"
export TOKEN="$TOKEN"
export ACCEPT_ADDR="$ACCEPT_ADDR"
export OPERATOR_ADDR="$OPERATOR_ADDR"
export GENESIS_ROOT="$GENESIS_ROOT"
EOV

echo ""
echo "State written to: $DEMO_STATE_ENV"
echo ""
echo "Next: start the demo sequencer -> scripts/demo_c_sequencer.sh"
