#!/usr/bin/env bash
set -euo pipefail

# Step B: deploy the demo contract stack.
#
# Deploys: AcceptAllVerifier (if not already deployed), PoseidonGoldilocks,
#          ToyUSDT (unless USDX_TOKEN_ADDRESS is set), TesseraContract.
# Uses AcceptAllVerifier for tx / deposit / withdrawal verifiers (zero proofs accepted).
#
# Environment overrides (optional):
#   ACCEPT_ADDR          -- skip AcceptAllVerifier deploy, reuse this address
#   USDX_TOKEN_ADDRESS   -- use an existing ERC20 instead of deploying ToyUSDT
#
# Prerequisites:
#   - Anvil running (scripts/demo_a_anvil.sh)
#   - forge + cast available

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/env/priv_env.sh"

mkdir -p "$DEMO_LOG_DIR"

echo ""
echo "Checking RPC connectivity: $RPC"
cast block-number --rpc-url "$RPC" >/dev/null

SOLIDITY_DIR="$ROOT_DIR/tessera-solidity"

pushd "$SOLIDITY_DIR" >/dev/null

# 1. Deploy AcceptAllVerifier (skip if ACCEPT_ADDR already set).
if [[ -n "${ACCEPT_ADDR:-}" ]]; then
  echo ""
  echo "Reusing existing AcceptAllVerifier = $ACCEPT_ADDR"
else
  echo ""
  echo "Deploying AcceptAllVerifier..."
  ACCEPT_OUT=$(forge create src/AcceptAllVerifier.sol:AcceptAllVerifier \
    --rpc-url "$RPC" \
    --private-key "$OPERATOR_KEY" \
    --broadcast 2>&1)
  echo "$ACCEPT_OUT"
  ACCEPT_ADDR=$(echo "$ACCEPT_OUT" | grep -oP 'Deployed to: \K0x[0-9a-fA-F]+')
  echo "  AcceptAllVerifier = $ACCEPT_ADDR"
fi

# 2. Deploy using the existing Deploy.s.sol.
#    - All three verifiers use AcceptAllVerifier (zero proofs accepted).
#    - If USDX_TOKEN_ADDRESS is set, reuse it as the monitored token (skip ToyUSDT deploy).
echo ""
if [[ -n "${USDX_TOKEN_ADDRESS:-}" ]]; then
  echo "Deploying full stack (PoseidonGoldilocks + TesseraContract + ToyUser) — reusing token $USDX_TOKEN_ADDRESS..."
  EXTRA_TOKEN_ENV="TESSERA_MONITORED_TOKEN=$USDX_TOKEN_ADDRESS"
else
  echo "Deploying full stack (PoseidonGoldilocks + ToyUSDT + TesseraContract + ToyUser)..."
  EXTRA_TOKEN_ENV=""
fi

env \
  TESSERA_TX_VERIFIER="$ACCEPT_ADDR" \
  TESSERA_DEPOSIT_VERIFIER="$ACCEPT_ADDR" \
  TESSERA_WITHDRAWAL_VERIFIER="$ACCEPT_ADDR" \
  TESSERA_POOL_CONFIG_ROOT="$POOL_CONFIG_ROOT" \
  TESSERA_TREE_DEPTH="$TREE_DEPTH" \
  ${EXTRA_TOKEN_ENV:+"$EXTRA_TOKEN_ENV"} \
forge script script/Deploy.s.sol \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast 2>&1

popd >/dev/null

# Parse deployed addresses from broadcast JSON.
BROADCAST_JSON="$SOLIDITY_DIR/broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"
if [[ ! -f "$BROADCAST_JSON" ]]; then
  echo "ERROR: broadcast file not found: $BROADCAST_JSON" >&2
  exit 1
fi

ROLLUP=$(jq -r '.transactions[] | select(.contractName == "TesseraContract") | .contractAddress' "$BROADCAST_JSON" | head -n1)

if [[ -z "${ROLLUP:-}" ]]; then
  echo "ERROR: failed to parse TesseraContract address." >&2
  exit 1
fi

# Use the pre-existing token if supplied, otherwise read the freshly-deployed ToyUSDT address.
if [[ -n "${USDX_TOKEN_ADDRESS:-}" ]]; then
  TOKEN="$USDX_TOKEN_ADDRESS"
else
  TOKEN=$(jq -r '.transactions[] | select(.contractName == "ToyUSDT") | .contractAddress' "$BROADCAST_JSON" | head -n1)
  if [[ -z "${TOKEN:-}" ]]; then
    echo "ERROR: failed to parse ToyUSDT address." >&2
    exit 1
  fi
fi

# Read genesis root from on-chain.
GENESIS_ROOT=$(cast call "$ROLLUP" "currentRoot()(uint256)" --rpc-url "$RPC" | tr -d '[:space:]' | sed 's/\[.*\]//')

# Derive operator address from key.
OPERATOR_ADDR=$(cast wallet address --private-key "$OPERATOR_KEY")

TOKEN_LABEL="${USDX_TOKEN_ADDRESS:+USDX (reused)}"
TOKEN_LABEL="${TOKEN_LABEL:-ToyUSDT (fresh)}"

echo ""
echo "=== Deployment summary ==="
echo "  AcceptAllVerifier  = $ACCEPT_ADDR"
echo "  TesseraContract    = $ROLLUP"
echo "  Token ($TOKEN_LABEL) = $TOKEN"
echo "  Operator           = $OPERATOR_ADDR"
echo "  Genesis root       = $GENESIS_ROOT"

# Write state file for subsequent scripts.
cat > "$DEMO_STATE_ENV" <<EOV
# Auto-generated by scripts/demo_b_deploy.sh
export ROLLUP="$ROLLUP"
export TOKEN="$TOKEN"
export ACCEPT_ADDR="$ACCEPT_ADDR"
export OPERATOR_ADDR="$OPERATOR_ADDR"
export GENESIS_ROOT="$GENESIS_ROOT"
EOV

echo ""
echo "State written to: $DEMO_STATE_ENV"
echo ""
echo "Next: start the demo sequencer -> scripts/demo_c_sequencer.sh"
