#!/usr/bin/env bash
set -euo pipefail

# Console D: register deposits on-chain, wait for them to be committed
# to the NC tree (Validated), then submit a private-tx that spends those notes and
# creates fresh output notes.  Verifies the full optimistic two-phase flow end-to-end.
# All on-chain and API interactions are driven by the `client` binary.
#
# Correct protocol semantics:
#   1. Deposits enter the NC tree via recordNotesCommitmentTreeUpdate (Pending → Validated).
#   2. A private tx spends already-committed (Validated) notes:
#        input_notes  = nullifiers of notes already in the NC tree
#        output_notes = fresh new note commitments (status None)
#   3. The tx_proof proves note validity (Plonky2 leaf proof generated by client).
#
# Two-phase optimistic flow:
#   Phase A — sequencer calls registerTransactionBatchUpdate():
#               all 4 latest roots advance immediately.
#               Notably: notesNullifierRoot advances (only the private tx does this).
#   Phase B — sequencer submits a single SuperAggregator Groth16 proof via confirmBatch();
#               all 4 confirmed*Roots advance atomically; TransactionBatchConfirmed fires.
#
# Args:
#   $1 total deposits     (default 256)
#   $2 request count      (default TESSERA_CONSUME_BATCH_SIZE; must be ≤ TESSERA_NOTE_BATCH_SIZE)
#   $3 optional env file  (default scripts/logs/tessera_e2e_latest.env)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Step 1: Load shared local environment variables (RPC, API URLs, keys, defaults).
source "$ROOT_DIR/scripts/local_env.sh"

# Step 2: Resolve runtime parameters with safe defaults.
TOTAL_DEPOSITS="${1:-256}"
REQUEST_COUNT="${2:-$TESSERA_CONSUME_BATCH_SIZE}"
E2E_ENV="${3:-$ROOT_DIR/scripts/logs/tessera_e2e_latest.env}"

# Step 3: Guardrail — REQUEST_COUNT must fit in a single batch (one /private-tx call).
if [[ "$REQUEST_COUNT" -gt "$TESSERA_NOTE_BATCH_SIZE" ]]; then
  echo "ERROR: request count ($REQUEST_COUNT) cannot exceed batch size ($TESSERA_NOTE_BATCH_SIZE)." >&2
  exit 1
fi

# Step 4: Guardrail — you cannot commit more notes than you deposit in this run.
if [[ "$REQUEST_COUNT" -gt "$TOTAL_DEPOSITS" ]]; then
  echo "ERROR: request count ($REQUEST_COUNT) cannot exceed deposits ($TOTAL_DEPOSITS)." >&2
  exit 1
fi

# Step 5: Ensure deployment metadata exists (produced by local_e2e_toy_b_deploy.sh).
if [[ ! -f "$E2E_ENV" ]]; then
  echo "ERROR: missing env file: $E2E_ENV" >&2
  echo "Run scripts/local_e2e_toy_b_deploy.sh first." >&2
  exit 1
fi

# Step 6: Load deployed contract addresses and actors (BRIDGE, TOKEN, TOY_USER).
# shellcheck disable=SC1090
source "$E2E_ENV"

# Step 7: Validate required deployment variables are available.
if [[ -z "${BRIDGE:-}" || -z "${TOKEN:-}" ]]; then
  echo "ERROR: BRIDGE/TOKEN missing in $E2E_ENV" >&2
  exit 1
fi

# Step 8: Wait for sequencer API readiness before sending real requests.
# Use a minimal POST that returns 200 (accepted or rejected) once the server is up.
# The dummy 1-byte proof is intentionally invalid; we only care about the HTTP status.
for _ in $(seq 1 20); do
  code=$(printf '{"note_commitment":"0x0000000000000000000000000000000000000000000000000000000000000001","input_proof":"0x01"}' \
    | curl -sS -o /dev/null -w "%{http_code}" -X POST "$TESSERA_SEQUENCER_API_URL/consume-request" \
      -H 'content-type: application/json' \
      --data-binary @- || true)
  if [[ "$code" == "200" || "$code" == "400" ]]; then
    break
  fi
  sleep 1
done

# Step 9: Prepare run-scoped log/output files.
LOG_DIR="$ROOT_DIR/scripts/logs"
mkdir -p "$LOG_DIR"
TS="$(date +%Y%m%d_%H%M%S)"
NOTES_FILE="$LOG_DIR/tessera_e2e_notes_${TS}.txt"
REQ_FILE="$LOG_DIR/tessera_e2e_requests_${TS}.txt"

# Export env vars expected by the client binary.
export TESSERA_RPC_URL="$RPC"
export TESSERA_OPERATOR_KEY="$OPERATOR_KEY"
export TESSERA_CLIENT_KEY="$CLIENT_KEY"
export TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS="$BRIDGE"
export TESSERA_MONITORED_TOKEN="$TOKEN"

# Step 10: Register deposits on-chain via the test client.
# The client mints tokens to the operator, approves the bridge, then calls
# bridge.depositAndRegister for each note index.
echo "Creating $TOTAL_DEPOSITS deposits via client (bridge.depositAndRegister)..."
cargo run --bin client --release --manifest-path "$ROOT_DIR/tessera-server/Cargo.toml" -- \
  deposit --count "$TOTAL_DEPOSITS" --start-index 1 --amount 1

# Populate NOTES_FILE and REQ_FILE (used later for on-chain status polling).
: > "$NOTES_FILE"
: > "$REQ_FILE"
for i in $(seq 1 "$TOTAL_DEPOSITS"); do
  NOTE=$(printf "0x%064x" "$i")
  echo "$NOTE" >> "$NOTES_FILE"
  if [[ "$i" -le "$REQUEST_COUNT" ]]; then
    echo "$NOTE" >> "$REQ_FILE"
  fi
done

# Step 11: Submit consume-requests via the test client.
# The client generates a Plonky2 proof per note (using TESSERA_CONSUME_ARTIFACTS_PATH
# when set; server accepts any non-empty proof when the path is unset).
echo "Queuing $REQUEST_COUNT deposits via client consume..."
cargo run --bin client --release --manifest-path "$ROOT_DIR/tessera-server/Cargo.toml" -- \
  consume --count "$REQUEST_COUNT" --start-index 1

# Preflight: wait for the NC commitment batch to commit and validate the deposits.
# The private tx can only spend notes that are already Validated on-chain (in the NC tree).
echo "Preflight: waiting for deposits to be committed to NC tree..."
deadline_pre=$((SECONDS + 300))
validated=0
while (( SECONDS < deadline_pre )); do
  validated=0
  while read -r NOTE; do
    STATUS=$(cast call "$BRIDGE" "getDepositStatus(bytes32)(uint8)" "$NOTE" \
      --rpc-url "$RPC" | tr -d '[:space:]')
    [[ "$STATUS" == "2" ]] && validated=$((validated + 1))
  done < "$REQ_FILE"
  echo "Preflight: $validated/$REQUEST_COUNT notes Validated"
  if [[ "$validated" -eq "$REQUEST_COUNT" ]]; then break; fi
  sleep 3
done
if [[ "$validated" -lt "$REQUEST_COUNT" ]]; then
  echo "ERROR: deposits not committed within preflight timeout." >&2
  exit 1
fi

# Step 12: Snapshot pre-submit state for all 6 roots (after deposit batch, before private tx).
# The NN root is the key sentinel for Phase A — only the private tx advances it.
NC_ROOT_BEFORE=$(cast call "$BRIDGE" "notesCommitmentRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
NN_ROOT_BEFORE=$(cast call "$BRIDGE" "notesNullifierRoot()(bytes32)"  --rpc-url "$RPC" | tr -d '[:space:]')
CONF_NC_BEFORE=$(cast call "$BRIDGE" "confirmedNotesCommitmentRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
CONF_NN_BEFORE=$(cast call "$BRIDGE" "confirmedNotesNullifierRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
CONF_AC_BEFORE=$(cast call "$BRIDGE" "confirmedAccountsCommitmentRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
CONF_AN_BEFORE=$(cast call "$BRIDGE" "confirmedAccountsNullifierRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
echo "notesCommitmentRoot before:             $NC_ROOT_BEFORE"
echo "notesNullifierRoot before:              $NN_ROOT_BEFORE"
echo "confirmedNotesCommitmentRoot before:    $CONF_NC_BEFORE"
echo "confirmedNotesNullifierRoot before:     $CONF_NN_BEFORE"
echo "confirmedAccountsCommitmentRoot before: $CONF_AC_BEFORE"
echo "confirmedAccountsNullifierRoot before:  $CONF_AN_BEFORE"

# Step 13: Submit a private-tx via the test client.
#
# The client generates random TX data (nullifiers, commitments, account mutations)
# and proves a 73-PI circuit proof from TESSERA_AGGREGATOR_ARTIFACTS_PATH.
echo "Submitting 1 private tx via client (random data)..."
_resp=$(cargo run --bin client --release --manifest-path "$ROOT_DIR/tessera-server/Cargo.toml" -- \
  private-tx --count 1)
echo "$_resp"
if ! echo "$_resp" | grep -qE ': accepted$'; then
  echo "ERROR: /private-tx not accepted." >&2
  exit 1
fi
unset _resp

# Step 14: Phase A — poll notesNullifierRoot() until it advances.
# notesNullifierRoot advances at register time (before any proof).  Only the
# private tx submits nullifiers, so this is the reliable Phase A sentinel.
echo "Phase A: waiting for notesNullifierRoot to advance (register on-chain)..."
deadline_a=$((SECONDS + 120))
NN_ROOT_AFTER="$NN_ROOT_BEFORE"
while (( SECONDS < deadline_a )); do
  NN_ROOT_AFTER=$(cast call "$BRIDGE" "notesNullifierRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
  if [[ "$NN_ROOT_AFTER" != "$NN_ROOT_BEFORE" ]]; then
    echo "Phase A: notesNullifierRoot advanced to $NN_ROOT_AFTER"
    break
  fi
  sleep 2
done
if [[ "$NN_ROOT_AFTER" == "$NN_ROOT_BEFORE" ]]; then
  echo "ERROR: notesNullifierRoot did not advance within Phase A timeout." >&2
  exit 1
fi

# Step 15: Phase B — poll all 4 confirmed roots until they all advance.
# A single SuperAggregator Groth16 proof is submitted via confirmBatch(), which advances
# all 4 confirmed roots atomically in one transaction.
# 1800 s generous upper bound for the single SuperAggregator prove + confirm.
echo "Phase B: waiting for all 4 tree proofs to be confirmed..."
nc=0; nn=0; ac=0; an=0
deadline_b=$((SECONDS + 1800))
while (( SECONDS < deadline_b )); do
  CONF_NC=$(cast call "$BRIDGE" "confirmedNotesCommitmentRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
  CONF_NN=$(cast call "$BRIDGE" "confirmedNotesNullifierRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
  CONF_AC=$(cast call "$BRIDGE" "confirmedAccountsCommitmentRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
  CONF_AN=$(cast call "$BRIDGE" "confirmedAccountsNullifierRoot()(bytes32)" --rpc-url "$RPC" | tr -d '[:space:]')
  nc=$([[ "$CONF_NC" != "$CONF_NC_BEFORE" ]] && echo 1 || echo 0)
  nn=$([[ "$CONF_NN" != "$CONF_NN_BEFORE" ]] && echo 1 || echo 0)
  ac=$([[ "$CONF_AC" != "$CONF_AC_BEFORE" ]] && echo 1 || echo 0)
  an=$([[ "$CONF_AN" != "$CONF_AN_BEFORE" ]] && echo 1 || echo 0)
  echo "Phase B confirmed: NC=$nc NN=$nn AC=$ac AN=$an"
  if [[ $nc -eq 1 && $nn -eq 1 && $ac -eq 1 && $an -eq 1 ]]; then
    echo "Phase B: all 4 tree proofs confirmed."
    break
  fi
  sleep 5
done
if [[ $((nc + nn + ac + an)) -lt 4 ]]; then
  echo "ERROR: timed out waiting for all 4 tree proofs to be confirmed." >&2
  exit 1
fi

# Step 16: Verify notesNullifierRoot changed (redundant sanity check; NN_ROOT_AFTER set in Phase A).
if [[ "$NN_ROOT_AFTER" == "$NN_ROOT_BEFORE" ]]; then
  echo "ERROR: notesNullifierRoot did not change after batch finalization." >&2
  exit 1
fi

# Step 17: Print success summary and artifact file locations.
echo ""
echo "E2E FLOW PASSED"
echo "BRIDGE=$BRIDGE"
echo "TOKEN=$TOKEN"
echo "NOTES_FILE=$NOTES_FILE"
echo "REQ_FILE=$REQ_FILE"
echo "Output notes: derived by client from random private key (Poseidon-hashed, not sequential indices)"

# Step 18: Print all deposits for manual auditing (status + raw tuple).
echo ""
echo "All deposits in contract (note_index 1..$TOTAL_DEPOSITS):"
for i in $(seq 1 "$TOTAL_DEPOSITS"); do
  NOTE=$(printf "0x%064x" "$i")
  dep=$(cast call "$BRIDGE" "getDeposit(bytes32)((uint256,address,uint8))" "$NOTE" --rpc-url "$RPC" 2>/dev/null || true)
  if [[ -z "$dep" ]]; then
    echo "note_index=$i note=$NOTE -> <missing>"
    continue
  fi
  status=$(echo "$dep" | sed -E 's/.*,[[:space:]]*([0-9]+)\)$/\1/')
  case "$status" in
    0) status_label="None" ;;
    1) status_label="Pending" ;;
    2) status_label="Validated" ;;
    3) status_label="Withdrawn" ;;
    *) status_label="Unknown($status)" ;;
  esac
  echo "note_index=$i note=$NOTE status=$status_label data=$dep"
done
