#!/usr/bin/env bash
set -euo pipefail

# Console B: deploy ToyUSDT + Bridge/Verifier + ToyUser and wire trusted source.
# Writes deployment outputs to: scripts/logs/tessera_e2e_latest.env

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/local_env.sh"

LOG_DIR="$ROOT_DIR/scripts/logs"
mkdir -p "$LOG_DIR"
OUT_ENV="$LOG_DIR/tessera_e2e_latest.env"

echo "Checking RPC connectivity: $RPC"
cast block-number --rpc-url "$RPC" >/dev/null

pushd "$ROOT_DIR/tessera-solidity" >/dev/null

echo "Deploying ToyUSDT..."
TOKEN=$(forge create src/ToyUSDT.sol:ToyUSDT \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast | sed -n 's/Deployed to: //p' | tail -n1)

if [[ -z "${TOKEN:-}" ]]; then
  echo "forge create failed to return token address, falling back to cast --create..."
  BYTECODE_TOKEN=$(forge inspect src/ToyUSDT.sol:ToyUSDT bytecode)
  DEPLOY_TOKEN_OUT=$(cast send \
    --rpc-url "$RPC" \
    --private-key "$OPERATOR_KEY" \
    --create "$BYTECODE_TOKEN")
  TOKEN=$(echo "$DEPLOY_TOKEN_OUT" | sed -n 's/^contractAddress[[:space:]]*//p' | head -n1)
fi

if [[ -z "${TOKEN:-}" ]]; then
  echo "ERROR: failed to deploy ToyUSDT." >&2
  exit 1
fi

echo "TOKEN=$TOKEN"

echo "Syncing Solidity verifier contracts from prover artifacts..."
"$ROOT_DIR/scripts/sync_verifiers_from_artifacts.sh"

echo "Deploying Verifier + Bridge..."
export TESSERA_TRUSTED_SOURCE="$TESSERA_TRUSTED_SOURCE"
export TESSERA_MONITORED_TOKEN="$TOKEN"
export TESSERA_NOTES_NULLIFIER_ROOT="$TESSERA_NOTES_NULLIFIER_ROOT"
export TESSERA_NOTES_COMMITMENT_ROOT="$TESSERA_NOTES_COMMITMENT_ROOT"
export TESSERA_BATCH_SIZE="$TESSERA_BATCH_SIZE"
DEPLOY_OUT=$(forge script script/pending-deposit/Deploy.s.sol \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast)

echo "$DEPLOY_OUT"
BRIDGE=$(echo "$DEPLOY_OUT" | sed -n 's/.*Bridge deployed at:[[:space:]]*//p' | tail -n1 | tr -d '\r')

if [[ -z "${BRIDGE:-}" ]]; then
  echo "ERROR: failed to parse bridge address from deploy output." >&2
  exit 1
fi

echo "BRIDGE=$BRIDGE"

echo "Deploying ToyUser (trusted-source adapter)..."
TRUSTED_SOURCE=$(
  forge create src/ToyUser.sol:ToyUser \
    --rpc-url "$RPC" \
    --private-key "$OPERATOR_KEY" \
    --broadcast \
    --constructor-args "$BRIDGE" "$TOKEN" | sed -n 's/Deployed to: //p' | tail -n1
)

if [[ -z "${TRUSTED_SOURCE:-}" ]]; then
  echo "forge create failed to return ToyUser address, falling back to cast --create..."
  # Note: Foundry project src path is set to src/pending-deposit in foundry.toml,
  # so `forge inspect src/ToyUser.sol:ToyUser ...` can fail. Inspect by contract name instead.
  BYTECODE_TS=$(forge inspect ToyUser bytecode)
  DEPLOY_TS_OUT=$(cast send \
    --rpc-url "$RPC" \
    --private-key "$OPERATOR_KEY" \
    --create "$BYTECODE_TS" \
    "constructor(address,address)" "$BRIDGE" "$TOKEN")
  TRUSTED_SOURCE=$(echo "$DEPLOY_TS_OUT" | sed -n 's/^contractAddress[[:space:]]*//p' | head -n1)
fi

if [[ -z "${TRUSTED_SOURCE:-}" ]]; then
  echo "ERROR: failed to parse ToyUser address from cast output." >&2
  echo "${DEPLOY_TS_OUT:-}"
  exit 1
fi

echo "TRUSTED_SOURCE=$TRUSTED_SOURCE"

cast send "$BRIDGE" "setTrustedSource(address)" "$TRUSTED_SOURCE" \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" >/dev/null

ACTUAL_TRUSTED=$(cast call "$BRIDGE" "trustedSource()(address)" --rpc-url "$RPC" | tr -d '[:space:]')
if [[ "${ACTUAL_TRUSTED,,}" != "${TRUSTED_SOURCE,,}" ]]; then
  echo "ERROR: trusted source mismatch after setTrustedSource." >&2
  exit 1
fi

popd >/dev/null

# Persist bridge for sequencer convenience.
SERVER_ENV="$ROOT_DIR/tessera-server/.env"
if [[ -f "$SERVER_ENV" ]]; then
  if grep -q '^TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=' "$SERVER_ENV"; then
    sed -i "s/^TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=.*/TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=$BRIDGE/" "$SERVER_ENV"
  else
    echo "TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=$BRIDGE" >> "$SERVER_ENV"
  fi
fi

cat > "$OUT_ENV" <<EOV
# Auto-generated by scripts/local_e2e_toy_b_deploy.sh
export RPC="$RPC"
export BRIDGE="$BRIDGE"
export TOKEN="$TOKEN"
export TRUSTED_SOURCE="$TRUSTED_SOURCE"
EOV

echo ""
echo "Deployment complete."
echo "State file: $OUT_ENV"
echo "Next:"
echo "  Console C (prover)    -> scripts/local_run_prover.sh"
echo "    Prover API          -> $TESSERA_PROVER_API_URL"
echo "  Console D (sequencer) -> scripts/local_e2e_toy_c_sequencer.sh"
echo "    Sequencer API       -> $TESSERA_SEQUENCER_API_URL"
echo "  Console E (flow)      -> scripts/local_e2e_toy_d_flow.sh 256 128"
