#!/usr/bin/env bash
set -euo pipefail

# Console B: deploy ToyUSDT + Bridge/Verifier + ToyTrustedSource and wire trusted source.
# Writes deployment outputs to: scripts/logs/tessera_e2e_latest.env

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/local_env.sh"

LOG_DIR="$ROOT_DIR/scripts/logs"
mkdir -p "$LOG_DIR"
OUT_ENV="$LOG_DIR/tessera_e2e_latest.env"

echo "Checking RPC connectivity: $RPC"
cast block-number --rpc-url "$RPC" >/dev/null

pushd "$ROOT_DIR/tessera-solidity" >/dev/null

echo "Deploying ToyUSDT..."
TOKEN=$(forge create src/pending-deposit/ToyUSDT.sol:ToyUSDT \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast | sed -n 's/Deployed to: //p' | tail -n1)

if [[ -z "${TOKEN:-}" ]]; then
  echo "forge create failed to return token address, falling back to cast --create..."
  BYTECODE_TOKEN=$(forge inspect src/pending-deposit/ToyUSDT.sol:ToyUSDT bytecode)
  DEPLOY_TOKEN_OUT=$(cast send \
    --rpc-url "$RPC" \
    --private-key "$OPERATOR_KEY" \
    --create "$BYTECODE_TOKEN")
  TOKEN=$(echo "$DEPLOY_TOKEN_OUT" | sed -n 's/^contractAddress[[:space:]]*//p' | head -n1)
fi

if [[ -z "${TOKEN:-}" ]]; then
  echo "ERROR: failed to deploy ToyUSDT." >&2
  exit 1
fi

echo "TOKEN=$TOKEN"

echo "Deploying Verifier + Bridge..."
export TESSERA_TRUSTED_SOURCE="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
export TESSERA_MONITORED_TOKEN="$TOKEN"
DEPLOY_OUT=$(forge script script/pending-deposit/Deploy.s.sol \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --broadcast)

echo "$DEPLOY_OUT"
BRIDGE=$(echo "$DEPLOY_OUT" | sed -n 's/.*Bridge deployed at:[[:space:]]*//p' | tail -n1 | tr -d '\r')

if [[ -z "${BRIDGE:-}" ]]; then
  echo "ERROR: failed to parse bridge address from deploy output." >&2
  exit 1
fi

echo "BRIDGE=$BRIDGE"

echo "Deploying ToyTrustedSource..."
BYTECODE_TS=$(forge inspect src/pending-deposit/ToyTrustedSource.sol:ToyTrustedSource bytecode)
DEPLOY_TS_OUT=$(cast send \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" \
  --create "$BYTECODE_TS" \
  "constructor(address,address)" "$BRIDGE" "$TOKEN")
TRUSTED_SOURCE=$(echo "$DEPLOY_TS_OUT" | sed -n 's/^contractAddress[[:space:]]*//p' | head -n1)

if [[ -z "${TRUSTED_SOURCE:-}" ]]; then
  echo "ERROR: failed to parse ToyTrustedSource address from cast output." >&2
  echo "$DEPLOY_TS_OUT"
  exit 1
fi

echo "TRUSTED_SOURCE=$TRUSTED_SOURCE"

cast send "$BRIDGE" "setTrustedSource(address)" "$TRUSTED_SOURCE" \
  --rpc-url "$RPC" \
  --private-key "$OPERATOR_KEY" >/dev/null

ACTUAL_TRUSTED=$(cast call "$BRIDGE" "trustedSource()(address)" --rpc-url "$RPC" | tr -d '[:space:]')
if [[ "${ACTUAL_TRUSTED,,}" != "${TRUSTED_SOURCE,,}" ]]; then
  echo "ERROR: trusted source mismatch after setTrustedSource." >&2
  exit 1
fi

popd >/dev/null

# Persist bridge for sequencer convenience.
SERVER_ENV="$ROOT_DIR/tessera-server/.env"
if [[ -f "$SERVER_ENV" ]]; then
  if grep -q '^TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=' "$SERVER_ENV"; then
    sed -i "s/^TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=.*/TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=$BRIDGE/" "$SERVER_ENV"
  else
    echo "TESSERA_PENDING_DEPOSIT_BRIDGE_ADDRESS=$BRIDGE" >> "$SERVER_ENV"
  fi
fi

cat > "$OUT_ENV" <<EOV
# Auto-generated by scripts/local_e2e_toy_b_deploy.sh
export RPC="$RPC"
export BRIDGE="$BRIDGE"
export TOKEN="$TOKEN"
export TRUSTED_SOURCE="$TRUSTED_SOURCE"
EOV

echo ""
echo "Deployment complete."
echo "State file: $OUT_ENV"
echo "Next:"
echo "  Console C -> scripts/local_e2e_toy_c_sequencer.sh"
echo "  Console D -> scripts/local_e2e_toy_d_flow.sh 256 128"
