#!/usr/bin/env bash
# Rebuilds Solidity contracts and regenerates doxa-e2e/src/contract_bytecodes.rs
# from the Foundry JSON artifacts.
#
# Usage: ./scripts/update_bytecodes.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOLIDITY_DIR="$REPO_ROOT/doxa-solidity"
OUT="$REPO_ROOT/doxa-e2e/src/contract_bytecodes.rs"

# Artifact paths (relative to doxa-solidity/)
declare -A ARTIFACTS=(
    [REJECT_BYTECODE]="out/DoxaContract.t.sol/RejectAllVerifier.json"
    [POSEIDON_BYTECODE]="out/PoseidonGoldilocks.sol/PoseidonGoldilocks.json"
    [ROLLUP_BYTECODE]="out/DoxaContract.sol/DoxaContract.json"
    [TOKEN_BYTECODE]="out/ToyUSDT.sol/ToyUSDT.json"
)

echo "Building Solidity contracts..."
(cd "$SOLIDITY_DIR" && forge build --force)

echo "Extracting bytecodes..."

# Extract bytecode (strip leading "0x")
extract_bytecode() {
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    bc = json.load(f)['bytecode']['object']
print(bc.removeprefix('0x'))
" "$1"
}

{
    echo '//! Contract bytecodes for E2E tests.'
    echo '//! Auto-generated by scripts/update_bytecodes.sh — do not edit manually.'
    echo ''
    # Emit in a stable order
    for name in REJECT_BYTECODE POSEIDON_BYTECODE ROLLUP_BYTECODE TOKEN_BYTECODE; do
        artifact="$SOLIDITY_DIR/${ARTIFACTS[$name]}"
        if [ ! -f "$artifact" ]; then
            echo "ERROR: artifact not found: $artifact" >&2
            exit 1
        fi
        bytecode="$(extract_bytecode "$artifact")"
        echo "pub const ${name}: &str = \"${bytecode}\";"
    done
} > "$OUT"

echo "Written $OUT ($(wc -c < "$OUT") bytes)"
