#!/usr/bin/env bash
# Build and deploy a demo group to a remote server via nginx + static files.
#
# Usage:
#   ./build_and_deploy.sh --group <slug> --server <user@host> --domain <domain>
#
# Example:
#   ./build_and_deploy.sh --group example --server ubuntu@1.2.3.4 --domain demo.tessera.xyz
#
# Prerequisites (local):  jq, node/npm, rsync
# Prerequisites (server): nginx, certbot (for wildcard TLS)
#
# DNS: point *.<domain> to the server's IP before running.
# TLS: the script generates nginx config; run certbot separately:
#   certbot certonly --dns-<provider> -d "*.<domain>" -d "<domain>"
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CW_DIR="$SCRIPT_DIR/client-wallet"
ADMIN_DIR="$SCRIPT_DIR/tessera-admin"
BUILD_DIR="$SCRIPT_DIR/.build"
GROUP=""
SERVER=""
DOMAIN=""

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --group)  GROUP="$2";  shift 2 ;;
    --server) SERVER="$2"; shift 2 ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ -z "$GROUP" || -z "$SERVER" || -z "$DOMAIN" ]]; then
  echo "Usage: $0 --group <slug> --server <user@host> --domain <domain>"
  exit 1
fi

GROUP_DIR="$SCRIPT_DIR/groups/$GROUP"
if [[ ! -d "$GROUP_DIR" ]]; then
  echo "Group '$GROUP' not found in $SCRIPT_DIR/groups/"
  exit 1
fi

command -v jq    >/dev/null 2>&1 || { echo "Error: jq is required";    exit 1; }
command -v rsync >/dev/null 2>&1 || { echo "Error: rsync is required"; exit 1; }

# ── Activate this group's institutions.json ───────────────────────────────────
cp "$GROUP_DIR/institutions.json" "$SCRIPT_DIR/institutions.json"

# ── Load group .env ───────────────────────────────────────────────────────────
set -a
# shellcheck source=/dev/null
source "$GROUP_DIR/.env"
set +a

# ── Build loop ────────────────────────────────────────────────────────────────
NGINX_BLOCKS=""
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

echo ""
echo "Building group: $GROUP  →  $DOMAIN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

while IFS= read -r hex; do
  slug=$(jq -r     --arg h "$hex" '.[$h].slug'     "$GROUP_DIR/ports.json")
  api_port=$(jq -r --arg h "$hex" '.[$h].api_port' "$GROUP_DIR/ports.json")

  wallet_host="${GROUP}-${slug}-wallet.${DOMAIN}"
  admin_host="${GROUP}-${slug}-admin.${DOMAIN}"

  wallet_out="$BUILD_DIR/wallet-${slug}"
  admin_out="$BUILD_DIR/admin-${slug}"

  # ── client-wallet ──────────────────────────────────────────────────────────
  echo ""
  echo "  [${slug}] Building client-wallet  → https://${wallet_host}"
  (
    cd "$CW_DIR"
    VITE_SUBPOOL_ID_HEX="$hex" \
    VITE_API_BASE_URL="https://${GROUP}-${slug}-api.${DOMAIN}" \
      npx vite build --outDir "$wallet_out" --emptyOutDir
  )

  # ── admin-dashboard ────────────────────────────────────────────────────────
  echo "  [${slug}] Building admin-dashboard → https://${admin_host}"
  (
    cd "$ADMIN_DIR"
    VITE_SUBPOOL_ID_HEX="$hex" \
    VITE_API_BASE_URL="https://${GROUP}-${slug}-api.${DOMAIN}" \
      npx vite build --outDir "$admin_out" --emptyOutDir
  )

  # ── nginx blocks ───────────────────────────────────────────────────────────
  NGINX_BLOCKS+="
# ── ${GROUP} / ${slug} ──────────────────────────────────────────────────────

server {
    listen 443 ssl;
    server_name ${wallet_host};
    root /var/www/${GROUP}/wallet-${slug};
    index index.html;
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    location / { try_files \$uri \$uri/ /index.html; }
}

server {
    listen 443 ssl;
    server_name ${admin_host};
    root /var/www/${GROUP}/admin-${slug};
    index index.html;
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    location / { try_files \$uri \$uri/ /index.html; }
}

server {
    listen 443 ssl;
    server_name ${GROUP}-${slug}-api.${DOMAIN};
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    location / {
        proxy_pass http://127.0.0.1:${api_port};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}

server {
    listen 80;
    server_name ${wallet_host} ${admin_host} ${GROUP}-${slug}-api.${DOMAIN};
    return 301 https://\$host\$request_uri;
}
"

done < <(jq -r 'keys[]' "$GROUP_DIR/ports.json")

# Write nginx config file
NGINX_CONF="$BUILD_DIR/${GROUP}.nginx.conf"
cat > "$NGINX_CONF" <<EOF
# Auto-generated by build_and_deploy.sh for group: ${GROUP}
# Place this file in /etc/nginx/sites-enabled/tessera-${GROUP}.conf
${NGINX_BLOCKS}
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Build complete. Deploying to ${SERVER}…"
echo ""

# ── Deploy ────────────────────────────────────────────────────────────────────

# Create remote web root dirs
while IFS= read -r hex; do
  slug=$(jq -r --arg h "$hex" '.[$h].slug' "$GROUP_DIR/ports.json")
  ssh "$SERVER" "mkdir -p /var/www/${GROUP}/wallet-${slug} /var/www/${GROUP}/admin-${slug}"
done < <(jq -r 'keys[]' "$GROUP_DIR/ports.json")

# Rsync built dist folders
while IFS= read -r hex; do
  slug=$(jq -r --arg h "$hex" '.[$h].slug' "$GROUP_DIR/ports.json")
  echo "  Uploading wallet-${slug}…"
  rsync -az --delete "$BUILD_DIR/wallet-${slug}/" "${SERVER}:/var/www/${GROUP}/wallet-${slug}/"
  echo "  Uploading admin-${slug}…"
  rsync -az --delete "$BUILD_DIR/admin-${slug}/"  "${SERVER}:/var/www/${GROUP}/admin-${slug}/"
done < <(jq -r 'keys[]' "$GROUP_DIR/ports.json")

# Upload nginx config and reload
echo "  Uploading nginx config…"
scp "$NGINX_CONF" "${SERVER}:/etc/nginx/sites-enabled/tessera-${GROUP}.conf"
ssh "$SERVER" "nginx -t && systemctl reload nginx"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Deployed! URLs:"
while IFS= read -r hex; do
  slug=$(jq -r --arg h "$hex" '.[$h].slug' "$GROUP_DIR/ports.json")
  echo "  Wallet : https://${GROUP}-${slug}-wallet.${DOMAIN}"
  echo "  Admin  : https://${GROUP}-${slug}-admin.${DOMAIN}"
  echo "  API    : https://${GROUP}-${slug}-api.${DOMAIN}  (proxy → backend)"
done < <(jq -r 'keys[]' "$GROUP_DIR/ports.json")
echo ""
echo "TLS: if not yet done, run on the server:"
echo "  certbot certonly --dns-<provider> -d \"*.${DOMAIN}\""
echo "  systemctl reload nginx"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
