// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {DepositsRollupBridge, IGroth16Verifier} from "../../src/pending-deposit/DepositsRollupBridge.sol";
import {Verifier} from "../../src/pending-deposit/Verifier.sol";

/// @title  Integration test: real Verifier + DepositsRollupBridge
/// @notice Loads a Groth16 proof and bridge calldata generated by the Rust
///         `groth16_wrapper` example and executes a full cycle:
///         deposit (on-chain) → finalizeBatch (Validated).
///
///         Artifact files (in groth-artifacts/):
///           - proof_solidity.json:  { proof[8], commitments[2], commitmentPok[2] }
///           - bridge_calldata.json: { oldRoot, newRoot, deposits[].commitment }
///
///         Prerequisites:
///           1. Regenerate artifacts with the new commitment format:
///              `cargo run -p tessera-server --example groth16_wrapper --release`
///           2. Run `forge test --match-contract Integration -vv`
///
/// @dev    This test requires artifacts generated with the new commitment format
///         (sha256(DOMAIN_SEP || noteCommitment || value || recipient) with MSB clearing).
///         Until artifacts are regenerated, this test will be skipped.
contract DepositsRollupBridgeIntegrationTest is Test {
    string constant ARTIFACTS = "../tessera-server/artifacts/pending-deposit/groth-artifacts/";

    uint256 constant BATCH_SIZE = 128;

    DepositsRollupBridge public bridge;
    Verifier public verifier;

    address public operator = address(this);

    // ---------------------------------------------------------------
    // Setup
    // ---------------------------------------------------------------

    function setUp() public {
        verifier = new Verifier();
    }

    // ---------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------

    struct ProofJson {
        uint256[8] proof;
        uint256[2] commitments;
        uint256[2] commitmentPok;
    }

    function _loadProofJson() internal view returns (ProofJson memory p) {
        string memory json = vm.readFile(
            string.concat(ARTIFACTS, "proof_solidity.json")
        );

        bytes memory rawProof = vm.parseJson(json, ".proof");
        uint256[] memory proofArr = abi.decode(rawProof, (uint256[]));
        for (uint256 i = 0; i < 8; i++) {
            p.proof[i] = proofArr[i];
        }

        bytes memory rawCommitments = vm.parseJson(json, ".commitments");
        uint256[] memory commArr = abi.decode(rawCommitments, (uint256[]));
        for (uint256 i = 0; i < 2; i++) {
            p.commitments[i] = commArr[i];
        }

        bytes memory rawPok = vm.parseJson(json, ".commitmentPok");
        uint256[] memory pokArr = abi.decode(rawPok, (uint256[]));
        for (uint256 i = 0; i < 2; i++) {
            p.commitmentPok[i] = pokArr[i];
        }
    }

    struct BridgeCalldata {
        bytes32 oldRoot;
        bytes32 newRoot;
    }

    function _loadBridgeCalldata() internal view returns (BridgeCalldata memory c) {
        string memory json = vm.readFile(
            string.concat(ARTIFACTS, "bridge_calldata.json")
        );

        c.oldRoot = vm.parseJsonBytes32(json, ".oldRoot");
        c.newRoot = vm.parseJsonBytes32(json, ".newRoot");
    }

    /// @dev Load deposit commitments from bridge_calldata.json and replay
    ///      them as on-chain deposits via bridge.deposit().
    function _loadAndDeposit() internal {
        string memory json = vm.readFile(
            string.concat(ARTIFACTS, "bridge_calldata.json")
        );

        for (uint256 i = 0; i < BATCH_SIZE; i++) {
            string memory base = string.concat(".deposits[", vm.toString(i), "]");
            bytes32 noteCommitment = vm.parseJsonBytes32(json, string.concat(base, ".noteCommitment"));
            uint256 value = vm.parseJsonUint(json, string.concat(base, ".value"));
            address recipient = vm.parseJsonAddress(json, string.concat(base, ".recipient"));
            bridge.deposit(noteCommitment, value, recipient);
        }
    }

    // ---------------------------------------------------------------
    // Integration test
    // ---------------------------------------------------------------

    /// @notice Full end-to-end test: deposit on-chain → finalizeBatch with the
    ///         real Groth16 verifier.
    /// @dev    Requires regenerated artifacts matching the new commitment format.
    function testIntegration_DepositAndFinalize() public {
        // 1. Load test data from Rust-generated artifacts.
        ProofJson memory proofData = _loadProofJson();
        BridgeCalldata memory callData = _loadBridgeCalldata();

        // 2. Deploy bridge with the real verifier and correct genesis root.
        bridge = new DepositsRollupBridge(
            address(verifier),
            operator,
            callData.oldRoot,
            BATCH_SIZE
        );
        assertEq(bridge.merkleRoot(), callData.oldRoot, "genesis root mismatch");

        // 3. Deposit all items on-chain.
        _loadAndDeposit();
        assertEq(bridge.nextDepositId(), BATCH_SIZE, "deposit count mismatch");

        // 4. Build the proof struct.
        DepositsRollupBridge.Proof memory proof;
        proof.proof = proofData.proof;
        proof.commitments = proofData.commitments;
        proof.commitmentPok = proofData.commitmentPok;

        // 5. Finalize — calls the real Verifier.
        bridge.finalizeBatch(callData.newRoot, 0, proof);

        // 6. Verify state was updated.
        assertEq(bridge.merkleRoot(), callData.newRoot, "root not updated");

        // 7. All deposits should be Validated.
        for (uint256 i = 0; i < BATCH_SIZE; i++) {
            DepositsRollupBridge.Deposit memory d = bridge.getDeposit(i);
            assertTrue(
                d.status == DepositsRollupBridge.DepositStatus.Validated,
                "deposit should be validated"
            );
        }
    }
}
